apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-dev-box
  labels:
    app: ubuntu
spec:
  restartPolicy: Never
  automountServiceAccountToken: false
  volumes:
  - name: home
    emptyDir:
      sizeLimit: 4Gi
  - name: docker-certs-ca
    emptyDir: {}
  - name: docker-certs-client
    emptyDir: {}
  initContainers:
  - name: change-home-dir-permissions
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    command: ["chmod", "-R", "og-w", "/home"]
    volumeMounts:
    - name: home
      mountPath: /home
  containers:
  # TODO: stop using DIND container, and just run the vanilla Ubuntu Server container as privileged
  - name: dind
    image: docker:dind
    securityContext:
      privileged: true
    command: ["dockerd", "--host", "tcp://127.0.0.1:2375"]
    env:
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    volumeMounts:
    - name: docker-certs-ca
      mountPath: /certs/ca
    - name: docker-certs-client
      mountPath: /certs/client
  - name: ubuntu
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sleep", "3650d"]
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    volumeMounts:
    - name: home
      mountPath: /home
    - name: docker-certs-client
      mountPath: /certs/client
      readOnly: true
