apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy
spec:
  # TODO: should only apply to Sinaia nodes
  #  nodeSelector:
  #    matchLabels:
  #      bgp-policy: a
  virtualRouters:
    - localASN: 64559
      neighbors:
        - peerAddress: "172.20.241.142/30"
          peerASN: 64559
      serviceSelector:
        matchExpressions:
          # We want to ensure all of our services which request load balancers get exported
          - {key: inexistent, operator: NotIn, values: ['never-used-value']}
