kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-sinaia
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  dataLocality: "best-effort"
  staleReplicaTimeout: "30" # in minutes
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/region
        values:
          - ro-sinaia-1
