apiVersion: v1
kind: Service
metadata:
  name: cilium-bgp-test-service
  annotations:
    "io.cilium/lb-ipam-ips": "10.45.250.250"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
