# Service Account for the global cluster admin user
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: default
---
# Appropriate (cluster) role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: default
