apiVersion: batch/v1
kind: Job
metadata:
  name: admitere-staging-run-migrations
  namespace: admission-app
spec:
  template:
    spec:
      imagePullSecrets:
        - name: admission-docker-registry-pull-secret
      containers:
        - name: admitere-staging-run-migrations
          image: registry.gitlab.com/unibuc/directia-itc/admission-app:main
          env:
            - name: RAILS_SERVE_STATIC_FILES
              value: "true"
            - name: MAILER_DEFAULT_URL
              value: admitere-staging.unibuc.ro
            - name: DATABASE_URL
              value: postgresql://admission-app-db:5432/admitere_staging
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: admitere-staging.admission-app-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admitere-staging.admission-app-db.credentials.postgresql.acid.zalan.do
                  key: password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: admitere-staging.secret-key-base
                  key: key
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: admitere-staging.admin-credentials
                  key: email
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admitere-staging.admin-credentials
                  key: password
          command: ["bundle", "exec", "rails", "db:migrate"]
      restartPolicy: Never
  backoffLimit: 1
