# Use this secret to store the GitLab Runner's token.
#
# Based on https://docs.gitlab.com/runner/install/kubernetes.html#store-registration-tokens-or-runner-tokens-in-secrets

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-runner
type: Opaque
data:
  runner-registration-token: "" # Need to leave as an empty string for compatibility reasons
  runner-token: "<put the actual token here>"
