controller:
  service:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: "10.45.250.100,10.45.250.101,10.45.250.102,10.45.250.103"
  metrics:
    enabled: true
  ingressClassResource:
    name: nginx-sinaia
    controllerValue: k8s.io/ingress-nginx-sinaia
  nodeSelector:
    kubernetes.io/os: linux
    topology.kubernetes.io/region: ro-sinaia-1
  replicaCount: 3
