# Certificate issuer using the Let's Encrypt staging environment
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: gabriel.majeri@unibuc.ro
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            # TODO: should also add one ingress class and issuer for Bucharest DC
            ingressClassName: nginx-sinaia
